config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("exercise/", include("stats.urls", namespace="exercise")),
    path("admin/", admin.site.urls),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
]

stats/urls.py
from django.urls import path
from . import views

app_name = "exercise"

urlpatterns = [
    path("main/", views.exercise, name="main"),
    path("squat/", views.squat, name="squat"),
]

users/urls.py
from django.urls import path
from . import views


app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification, name="complete-verification"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("update-record/", views.UpdateRecordView.as_view(), name="updaterecord"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.11.2/css/all.css"
    />
    <title>{% block page_name %}{% endblock page_name %} | AI Trainer</title>
  </head>

  <body class="text-gray-800 mt-24">
    {% include 'partials/messages.html' %}
    
    <header
      class="container max-w-full flex items-center justify-between px-6 h-20 border-b border-gray-400 bg-white fixed inset-0"
    >
    {% include "partials/nav.html" %}
    </header>

    <div>
      {% block content %}{% endblock content %}
    </div>

    {% include "partials/footer.html" %}
  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block page_name %}Home{% endblock page_name %}

{% block content %}
<div
  class="container rounded-xl mx-auto bg-gray-800 h-50vh mb-10 mt-24 bg-cover bg-center"
  style="
    background-image: url(https://images.unsplash.com/photo-1461896836934-ffe607ba8211?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80);
  "
></div>
<div class="container mx-auto h-25vh w-full">
  <ul class="flex items-center h-full w-full justify-between">
    
    <li class="bg-gray-200 w-2/6 h-25vh mx-2 ml-0 flex items-center justify-center rounded-xl bg-cover bg-center shadow-md hover:shadow-lg">
        {% if user.is_authenticated %}
          <a class="h-full w-full" href="{{user.get_absolute_url}}">STATUS</a>
        {% else %}
          <a class="h-full w-full" href="{% url "users:login" %}">STATUS</a>
        {% endif %}
    </li>    
    <li
      class="bg-gray-200 w-2/6 h-25vh mx-2 flex items-center justify-center rounded-xl bg-cover bg-center shadow-md hover:shadow-lg"
      style="
        background-image: url(https://images.unsplash.com/photo-1516820612845-a13894592046?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80);
      "
    >
      <a class="h-full w-full" href="">PLAN</a>
    </li>
    <li
      class="bg-gray-200 w-2/6 h-25vh mx-2 mr-0 flex items-center justify-center rounded-xl bg-cover bg-center shadow-md hover:shadow-lg"
    >
      <a class="h-full w-full" href="{% url "exercise:main" %}">>EXERCISE</a>
    </li>
  </ul>
</div>

{% endblock content %}