config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("exercise/", include("stats.urls", namespace="exercise")),
    path("admin/", admin.site.urls),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
]

users/urls.py
from django.urls import path
from . import views


app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification, name="complete-verification"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("update-record/", views.UpdateRecordView.as_view(), name="updaterecord"),
]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . import models


class LoginForm(forms.Form):

    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )

    # for validation(is_valid), "clean_" 뒤에 위의 폼 변수

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is worng"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User does not exist"))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("first_name", "last_name", "email")
        widgets = {
            "first_name": forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
            "email": forms.EmailInput(attrs={"placeholder": "Email"}),
        }

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"})
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError(
                "That email is already taken", code="existing_user"
            )
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        if password != password1:
            raise forms.ValidationError("Password confirmation does not match")
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()

users/views.py
import os
import requests
from django.views import View
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import FormView, DetailView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from . import forms, models, mixins


class LoginView(mixins.LoggedOutOnlyView, SuccessMessageMixin, FormView):

    template_name = "users/login.html"
    form_class = forms.LoginForm
    success_message = "Welecome back!"

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def log_out(request):
    logout(request)
    messages.info(request, f"See you later")
    return redirect(reverse("core:home"))


class SignUpView(mixins.LoggedOutOnlyView, SuccessMessageMixin, FormView):
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")
    success_message = "Welecome!"

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        user.verify_email()
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
        # to do: add success message
    except models.User.DoesNotExist:
        # to do: add error message
        pass
    return redirect(reverse("core:home"))


def github_login(request):
    client_id = os.environ.get("GH_ID")
    redirect_uri = "http://127.0.0.1:8000/users/login/github/callback"
    return redirect(
        f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user"
    )


class GithubException(Exception):
    pass


def github_callback(request):
    try:
        client_id = os.environ.get("GH_ID")
        client_secret = os.environ.get("GH_SECRET")
        code = request.GET.get("code", None)
        if code is not None:
            token_request = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
            )
            token_json = token_request.json()
            error = token_json.get("error", None)
            if error is not None:
                raise GithubException("Can't get access token")
            else:
                access_token = token_json.get("access_token")
                profile_request = requests.get(
                    "https://api.github.com/user/emails",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                profile_json = profile_request.json()
                username = profile_json.get("login", None)
                if username is not None:
                    name = profile_json.get("name")
                    email = profile_json.get("email")
                    bio = profile_json.get("bio")
                    try:
                        user = models.User.objects.get(email=email)
                        if user.login_method != models.User.LOGIN_GITHUB:
                            raise GithubException(
                                f"Please log in with: {user.login_method}"
                            )
                    except models.User.DoesNotExist:
                        user = models.User.objects.create(
                            email=email,
                            first_name=name,
                            username=email,
                            bio=bio,
                            login_method=models.User.LOGIN_GITHUB,
                            email_verified=True,
                        )
                        user.set_unusable_password()
                        user.save()
                    login(request, user)
                    messages.success(request, f"Welecome back {user.first_name}")
                    return redirect(reverse("core:home"))
                else:
                    raise GithubException("Can't get your profile")
        else:
            raise GithubException("Can't get code")
    except GithubException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


def kakao_login(requset):
    client_id = os.environ.get("KAKAO_ID")
    redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    try:
        code = request.GET.get("code")
        client_id = os.environ.get("KAKAO_ID")
        redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
        token_request = requests.get(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}"
        )
        token_json = token_request.json()
        error = token_json.get("error", None)
        if error is not None:
            raise KakaoException("Can't get authorization code")
        access_token = token_json.get("access_token")
        profile_request = requests.get(
            "https://kapi.kakao.com/v2/user/me",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        profile_json = profile_request.json()
        print(profile_json)
        email = profile_json.get("kakao_account", None).get("email", None)
        if email is None:
            raise KakaoException("Please also give me your email")
        properties = profile_json.get("properties")
        nickname = properties.get("nickname")
        try:
            user = models.User.objects.get(email=email)
            if user.login_method != models.User.LOGIN_KAKAO:
                raise KakaoException(f"Please log in with: {user.login_method}")
        except models.User.DoesNotExist:
            user = models.User.objects.create(
                email=email,
                username=email,
                first_name=nickname,
                login_method=models.User.LOGIN_KAKAO,
                email_verified=True,
            )
            user.set_unusable_password()
            user.save()
        login(request, user)
        messages.success(request, f"Welecome back {user.first_name}")
        return redirect(reverse("core:home"))
    except KakaoException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


class UserProfileView(DetailView):

    model = models.User
    context_object_name = "user_obj"


class UpdateProfileView(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):
    model = models.User
    template_name = "users/update-profile.html"
    fields = (
        "first_name",
        "last_name",
        "school",
        "grade",
        "group",
        "number",
        "age",
        "gender",
        "bio",
    )
    success_message = "Profile Updated"

    def get_object(self, queryset=None):
        return self.request.user

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["first_name"].widget.attrs = {"placeholder": "First name"}
        form.fields["last_name"].widget.attrs = {"placeholder": "Last name"}
        form.fields["school"].widget.attrs = {"placeholder": "School"}
        form.fields["grade"].widget.attrs = {"placeholder": "Grade"}
        form.fields["group"].widget.attrs = {"placeholder": "Group"}
        form.fields["number"].widget.attrs = {"placeholder": "Number"}
        form.fields["age"].widget.attrs = {"placeholder": "Age"}
        form.fields["gender"].widget.attrs = {"placeholder": "Gender"}
        form.fields["bio"].widget.attrs = {"placeholder": "Bio"}
        return form


class UpdatePasswordView(
    mixins.EmailLoginOnlyView,
    mixins.LoggedInOnlyView,
    SuccessMessageMixin,
    PasswordChangeView,
):

    template_name = "users/update-password.html"
    success_message = "Password Updated"

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["old_password"].widget.attrs = {"placeholder": "Current password"}
        form.fields["new_password1"].widget.attrs = {"placeholder": "New password"}
        form.fields["new_password2"].widget.attrs = {
            "placeholder": "Confirm new password"
        }
        return form

    def get_success_url(self):
        return self.request.user.get_absolute_url()


class UpdateRecordView(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):
    model = models.User
    template_name = "users/update-record.html"
    fields = (
        "pacer",
        "longTimeRun",
        "stepTest",
        "bendFoward",
        "totalFlexibility",
        "sitUp",
        "grip",
        "sprint",
        "longJump",
        "height",
        "weight",
    )
    success_message = "Record Updated"

    def get_object(self, queryset=None):

templates/users/login.html
{% extends "base.html" %}

{% block page_name %}
Login
{% endblock page_name %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'partials/social_login.html' %}

        {% include 'mixins/auth/auth_form.html' with form=form cta="Log in" %}

        <div class="mt-5">
            <span class="mr-2">Don't have an account?</span>
            <a href="{% url "users:signup" %}" class="text-teal-500 font-medium">Sign up</a>
        </div>
    </div>


{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}

{% block page_name %}
Sign Up
{% endblock page_name %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'partials/social_login.html' %}


        {% include 'mixins/auth/auth_form.html' with form=form cta="Sign up" %}

        <div class="mt-5">
            <span class="mr-2">Have an account?</span>
            <a href="{% url "users:login" %}" class="text-teal-500 font-medium">Log in</a>
        </div>

    </div>

{% endblock content %}

templates/users/update-password.html
{% extends "base.html" %}

{% block page_title %}
    Update Password
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="min-h-75vh">
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
            {% include 'mixins/auth/auth_form.html' with form=form cta="Update Password" %}
    </div>
</div>
{% endblock content %} 

templates/users/update-profile.html
{% extends "base.html" %}

{% block page_name %}
    Update Profile
{% endblock page_name %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/auth/auth_form.html' with form=form cta="Update profile" %}

        {% if object.login_method == "email" %}
            <div class="mt-5">
                <a href="{% url 'users:password' %}" class="text-teal-500 font-medium">Change Password</a>
            </div>
        {% endif %}

    </div>
{% endblock content %} 

templates/users/update-record.html
{% extends "base.html" %}

{% block page_name %}
    Update Record
{% endblock page_name %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/stats/stat_form.html' with form=form cta="Update record" %}



    </div>
{% endblock content %} 

templates/users/user_detail.html
{% extends "base.html" %}

{% block page_name %}
    {{user_obj.first_name}}'s Profile
{% endblock page_name %}

{% block content %}
     
    <div class="min-h-75vh w-full flex flex-col items-center">
            <div class="container w-full flex justify-between mx-auto">
                <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto flex flex-col items-center border p-6 border-gray-400">
        
                    {% include "mixins/user_avatar.html" with user=user_obj %}
            
                    <div class="flex items-center">
                        <span class="text-3xl mt-1">{{user_obj.first_name}}</span>
                    </div>
            
                    <span class="text-lg mb-5">{{user.bio}}</span>
            
                    {% if user == user_obj %}
                        <a href="{% url "users:update" %}" class="btn-link mb-3">Edit Profile</a>
                        <a href="{% url "users:updaterecord" %}" class="btn-link mb-3">Edit Records</a>
                    {% endif %}
                </div>
                
                <div class="container lg:w-5/12 md:w-1/2 xl:w-8/12 mx-auto flex items-center border border-gray-400">
                    <span>
                        <i class="fas fa-medal text-yellow-400 fa-10x"></i>
                    </span>
                    <span>
                        My health score is point!
                    </span>
                </div>
            </div>
            

            
            <div class="container lg:w-5/12 md:w-1/2 xl:w-full mx-auto my-10 py-10 flex flex-col items-start justify-around border p-6 border-gray-400">
                <div class="lg:w-5/12 md:w-1/2 xl:w-full flex items-start">
                    {% include 'users/user_stat.html' %}
                </div>

                <div class="flex items-center lg:w-5/12 md:w-1/2 xl:w-full my-5">
                    <div class="h-px w-full bg-gray-400"></div>
                    <span class="text-gray-600 font-medium mx-4 text-sm">Rating</span>
                    <div class="h-px w-full bg-gray-400"></div>
                </div>

                <div class="container lg:w-5/12 md:w-1/2 xl:w-full mx-auto flex items-center justify-around">
                    <span class="text-center w-full border border-gray-400 py-2 mr-4 rounded-md">심폐지구력</span>
                    <span class="text-center w-full border border-gray-400 mx-3 py-2 ml-4 rounded-md">유연성</span>
                    <span class="text-center w-full border border-gray-400 mx-6 py-2 px--2 rounded-md">근력 및 근지구력</span>
                    <span class="text-center w-full border border-gray-400 mx-3 py-2 mr-4 rounded-md">순발력</span>
                    <span class="text-center w-full border border-gray-400 py-2 ml-4 rounded-md">비만</span>
                </div>

                <div class="container lg:w-5/12 md:w-1/2 xl:w-full mx-auto flex items-center justify-around mt-3">
                    <span class="text-center w-full border border-gray-400 py-2 mr-4 rounded-md">{{user_obj.endurance_point}}등급</span>
                    <span class="text-center w-full border border-gray-400 mx-3 py-2 ml-4 rounded-md">{{user_obj.flexibility_point}}등급</span>
                    <span class="text-center w-full border border-gray-400 mx-6 py-2 px--2 rounded-md">{{user_obj.strength_point}}등급</span>
                    <span class="text-center w-full border border-gray-400 mx-3 py-2 mr-4 rounded-md">{{user_obj.quickness_point}}등급</span>
                    <span class="text-center w-full border border-gray-400 py-2 ml-4 rounded-md">{{user_obj.fat_point}}</span>
                </div>
            </div>      
    </div>
{% endblock content %}

templates/users/user_stat.html
<div class="w-full flex items-start">
    <ul class="stat w-1/6">
        <li class="w-full">pacer
            
            {% if user.pacer %}
                <i class="fas fa-check-circle text-teal-400 ml-1"></i>
            {% endif %}
                
        </li>
        <li class="w-full">longTimeRun
            {% if user.longTimeRun %}
                <i class="fas fa-check-circle text-teal-400 ml-1"></i>
            {% endif %}
        </li>
        <li class="w-full">stepTest
            {% if user.stepTest %}
                <i class="fas fa-check-circle text-teal-400 ml-1"></i>
            {% endif %}
        </li>
    </ul>
    <ul class="stat w-1/12 mr-10">
        <li class="w-full">
            {% if user.pacer == None %}
                -
            {% else %}
                {{user.pacer}}
            {% endif %}       
        </li>
        <li class="w-full">
            {% if user.longTimeRun == None %}
                -
            {% else %}
                {{user.longTimeRun}}
            {% endif %}
        </li>
        <li class="w-full">
            {% if user.stepTest == None %}
                -
            {% else %}
                {{user.stepTest}}
            {% endif %}
        </li>
    </ul>
    <ul class="stat w-1/6">
        <li class="w-full">bendFoward
            {% if user.bendFoward %}
                <i class="fas fa-check-circle text-teal-400 ml-1"></i>
            {% endif %}
        </li>
        <li class="w-full">totalFlexibility
            {% if user.totalFlexibility %}
                <i class="fas fa-check-circle text-teal-400 ml-1"></i>
            {% endif %}
        </li>
    </ul>
    <ul class="stat w-1/12 mr-10">
        <li>
            {% if user.bendFoward == None %}
                -
            {% else %}
                {{user.bendFoward}}
            {% endif %}
        </li>
        <li>
            {% if user.totalFlexibility == None %}
                -
            {% else %}
                {{user.totalFlexibility}}
            {% endif %}
        </li>
    </ul>
    <ul class="stat w-1/6">
        {% comment %} <li>pushUp
            {% if user.pushUp %}
                <i class="fas fa-check-circle text-teal-400 ml-1"></i>
            {% endif %}
        </li> {% endcomment %}
        <li>sitUp
            {% if user.sitUp %}
                <i class="fas fa-check-circle text-teal-400 ml-1"></i>
            {% endif %}
        </li>
        <li>grip
            {% if user.grip %}
                <i class="fas fa-check-circle text-teal-400 ml-1"></i>
            {% endif %}
        </li>
    </ul>
    <ul class="stat w-1/12 mr-10">
        {% comment %} <li>
            {% if user.pushUp == None %}
                -
            {% else %}
                {{user.pushUp}}
            {% endif %}
        </li> {% endcomment %}
        <li>
            {% if user.sitUp == None %}
                -
            {% else %}
                {{user.sitUp}}
            {% endif %}
        </li>
        <li>
            {% if user.grip == None %}
                -
            {% else %}
                {{user.grip}}
            {% endif %}
        </li>
    </ul>
    <ul class="stat w-1/6">
        <li>sprint
            {% if user.sprint %}
                <i class="fas fa-check-circle text-teal-400 ml-1"></i>
            {% endif %}
        </li>
        <li>longJump
            {% if user.longJump %}
                <i class="fas fa-check-circle text-teal-400 ml-1"></i>
            {% endif %}
        </li>
    </ul>
    <ul class="stat w-1/12 mr-10">
        <li>
            {% if user.sprint == None %}
                -
            {% else %}
                {{user.sprint}}
            {% endif %}
        </li>
        <li>
            {% if user.longJump == None %}
                -
            {% else %}
                {{user.longJump}}
            {% endif %}
        </li>
    </ul>
    <ul class="stat w-1/6">
        <li>height
            {% if user.height %}
                <i class="fas fa-check-circle text-teal-400 ml-1"></i>
            {% endif %}
        </li>
        <li>weight
            {% if user.weight %}
                <i class="fas fa-check-circle text-teal-400 ml-1"></i>
            {% endif %}
        </li>
        {% comment %} <li>fat
            {% if user.fat %}
                <i class="fas fa-check-circle text-teal-400 ml-1"></i>
            {% endif %} {% endcomment %}
        </li>
    </ul>
    <ul class="stat w-1/12">
        <li>
            {% if user.height == None %}
                -
            {% else %}
                {{user.height}}
            {% endif %}
        </li>
        <li>
            {% if user.weight == None %}
                -
            {% else %}
                {{user.weight}}
            {% endif %}
        </li>
        {% comment %} <li>
            {% if user.fat == None %}
                -
            {% else %}
                {{user.fat}}
            {% endif %}
        </li> {% endcomment %}
    </ul>
</div>